export const EN_LANG = "en";

export const EN_TRANSLATION = {
  LOG_IN: "Log in",
  LOG_OUT: "Log out",
  ORDER_NOW: "Order now",
  HEALTHIER_OPTIONS: "HEALTHIER OPTIONS",
  WITH_EVERY_SIP: "WITH EVERY SIP",
  MADE_WITH_HOMEMADE_PURE_SOY_MILK: "Made with homemade pure soy milk",
  PERFECT_FOR_VEGANS_AND_LACTOSE_INTOLERANT:
    "Perfect for vegans and lactose intolerant",
  LOGIN_WITH_EMAIL: "Login with Email",
  LOGIN_WITH_GOOGLE: "Login with Google",
  SIGN_UP_WITH_EMAIL: "Sign up with Email",
  SIGN_UP_WITH_GOOGLE: "Sign up with Google",
  WELCOME: "WELCOME",
  BACK: "BACK",
  EMAIL: "Email",
  YOUR_EMAIL_ACCOUNT: "Your email account",
  PASSWORD: "Password",
  YOUR_PASSWORD: "Your password",
  CANT_REMEBER_MY_PASSWORD: "Can't remember my password",
  DONT_HAVE_AN_ACCOUNT_CREATE_ONE: "Don't have an account? Create one ",
  EMAIL_SENT_CHECK_YOUR_MAILBOX: "Email sent. Check your mailbox.",
  ERROR_FILL_IN_YOUR_EMAIL_IN_THE_FORM_FIRST:
    "Error: Fill in your email in the form first.",
  HERE: "here",
  NICE_TO: "NICE TO",
  MEET_YOU: "MEET YOU",
  MAKE_THE_PASSWORD: "Make the password",
  NEW_PASSWORD: "New password",
  FULL_NAME: "Full name",
  YOUR_FULL_NAME: "Your full name",
  SIGN_UP: "Sign up",
  HELLO: "HELLO",
  REPEAT_AN_ORDER: "Repeat an order",
  MY_ORDERS: "My orders",
  MY: "MY",
  ORDERS: "ORDERS",
  SOJA_LOVERS: "Soja Lovers",
  LANGUAGE: "Language",
  FOLLOW_US: "Follow us",
  YOU_ARE_NOT: "YOU ARE NOT",
  LOGGED_IN: "LOGGED IN",
  VIEW_ORDER: "View order",
  YOUR_ORDER: "YOUR ORDER",
  SIP_IN: "Sip in",
  TAKE_AWAY: "Take away",
  SUMMARY: "Summary",
  TOTAL: "Total",
  CONFIRM_ORDER: "Confirm order",
  MY_ORDER_1: "My order (1)",
  DELETE_ORDER: "Delete order",
  COLD_OR_HOT: "COLD OR HOT?",
  HOW_SWEET: "HOW SWEET?",
  RECENT: "Recent",
  NO_ORDER_HISTORY: "No order history",
  REPEAT: "Repeat",
  SOJA: "SOJA",
  LOVERS: "LOVERS",
  ORDER_10_BUBBLE_TEAS: "Order 10 Bubble Teas and get the 11th for free",
  NO_PRODUCTS_IN_THE_CART: "You dont have any product in the cart",
  // descriptions
  STRAWBERRY_DESCRIPTION: "Strawberries, soy milk, tapioca balls.",
  BANANA_DESCRIPTION: "Bananas, soy milk, tapioca balls.",
  MANGO_DESCRIPTION: "Mango, with soy milk, tapioca balls.",
  TARO_MATCHA_DESCRIPTION: "Taro, matcha, soy milk, tapioca balls.",
  TARO_DESCRIPTION: "Taro, soy milk, tapioca balls.",
  MANGO_GRAPEFRUIT_DESCRIPTION: "Mango, grapefruit, soy milk, tapioca balls.",
  YAKULT_PEACH_DESCRIPTION: "Yakult, peach chunks, tapioca balls.",
  YAKULT_LITCHI_DESCRIPTION: "Yakult, litchi, tapioca balls.",
  YAKULT_GRAPEFRUIT_DESCRIPTION: "Yakult, grapefruit chunks, tapioca balls.",
  YAKULT_PASSION_FRUIT_DESCRIPTION: "Yakult, passion fruit, tapioca balls.",
  SOY_MILK_DESCRIPTION: "Soy milk, tapioca balls.",
  JASMINE_LATTE_DESCRIPTION: "Jasmine, soy milk, tapioca balls.",
  BLACK_TEA_LATTE_DESCRIPTION: "Black tea, soy milk, tapioca balls.",
  MATCHA_LATTE_DESCRIPTION: "Matcha, soy milk, tapioca balls.",
  BLACK_TEA_WITH_CREAM_DESCRIPTION:
    "Black tea, soy milk, soy cream, tapioca balls.",
  JASMINE_WITH_CREAM_DESCRIPTION:
    "Jasmine tea, soy milk, soy cream, tapioca balls.",
  OOLONG_WITH_CREAM_DESCRIPTION:
    "Oolong tea, soy milk, soy cream, tapioca balls.",
  sugar50: "50% sugar",
  sugar0: "no sugar",
  sugar30: "30% sugar",
  sugar70: "70% sugar",
  hot45: "hot (45°C)",
  hot60: "hot (60°C)",
  noIce: "without ice",
  lessIce: "less ice",
  regularIce: "regular ice",
};
