export const ES_LANG = "es";
export const ES_TRANSLATION = {
  LOG_IN: "Iniciar sesión",
  LOG_IN_CON: "Entrar con",
  LOG_OUT: "Desconectar",
  ORDER_NOW: "Pide ahora",
  HEALTHIER_OPTIONS: "OPCIONES SALUDABLES",
  WITH_EVERY_SIP: "CON CADA SORBO",
  MADE_WITH_HOMEMADE_PURE_SOY_MILK: "Elaborado con leche de soja pura casera",
  PERFECT_FOR_VEGANS_AND_LACTOSE_INTOLERANT: "Perfecto para veganos e intolerantes a la lactosa",
  LOGIN_WITH_EMAIL: "Entrar con Email",
  LOGIN_WITH_GOOGLE: "Entrar con Google",
  SIGN_UP_WITH_EMAIL: "Crear cuenta con Email",
  SIGN_UP_WITH_GOOGLE: "Crear cuenta con Google",
  WELCOME: "BIENVENID@",
  BACK: "DE NUEVO",
  EMAIL: "Email",
  YOUR_EMAIL_ACCOUNT: "Tu cuenta de email",
  PASSWORD: "Contraseña",
  YOUR_PASSWORD: "Tu contraseña",
  CANT_REMEBER_MY_PASSWORD: "He olvidado mi contraseña",
  DONT_HAVE_AN_ACCOUNT_CREATE_ONE: "¿No tienes cuenta? Crear cuenta ",
  EMAIL_SENT_CHECK_YOUR_MAILBOX: "Correo electrónico enviado. Revisa tu bandeja de entrada.",
  ERROR_FILL_IN_YOUR_EMAIL_IN_THE_FORM_FIRST: "Error: Completa tu correo electrónico en el formulario primero.",
  HERE: "aquí",
  NICE_TO: "MUCHO",
  MEET_YOU: "GUSTO",
  MAKE_THE_PASSWORD: "Crea una contraseña",
  FULL_NAME: "Nombre completo",
  YOUR_FULL_NAME: "Tu nombre completo",
  SIGN_UP: "Crear cuenta",
  HELLO: "HOLA",
  REPEAT_AN_ORDER: "Repite un pedido",
  MY_ORDERS: "Mis pedidos",
  SOJA_LOVERS: "Soja Lovers",
  LANGUAGE: "Idioma",
  FOLLOW_US: "Síguenos",
  FOLLOW_US1: "Síguenos1",
  YOU_ARE_NOT: "NO ESTAS",
  LOGGED_IN: "LOGUEADO",
};
