export const ES_LANG = "es";
export const ES_TRANSLATION = {
  LOG_IN: "Iniciar sesión",
  LOG_IN_CON: "Entrar con",
  LOG_OUT: "Desconectar",
  ORDER_NOW: "Pide ahora",
  HEALTHIER_OPTIONS: "OPCIONES SALUDABLES",
  WITH_EVERY_SIP: "CON CADA SORBO",
  MADE_WITH_HOMEMADE_PURE_SOY_MILK: "Elaborado con leche de soja pura casera",
  PERFECT_FOR_VEGANS_AND_LACTOSE_INTOLERANT:
    "Perfecto para veganos e intolerantes a la lactosa",
  LOGIN_WITH_EMAIL: "Entrar con Email",
  LOGIN_WITH_GOOGLE: "Entrar con Google",
  SIGN_UP_WITH_EMAIL: "Crear cuenta con Email",
  SIGN_UP_WITH_GOOGLE: "Crear cuenta con Google",
  WELCOME: "BIENVENID@",
  BACK: "DE NUEVO",
  EMAIL: "Email",
  YOUR_EMAIL_ACCOUNT: "Tu cuenta de email",
  PASSWORD: "Contraseña",
  YOUR_PASSWORD: "Tu contraseña",
  CANT_REMEBER_MY_PASSWORD: "He olvidado mi contraseña",
  DONT_HAVE_AN_ACCOUNT_CREATE_ONE: "¿No tienes cuenta? Crear cuenta ",
  EMAIL_SENT_CHECK_YOUR_MAILBOX:
    "Correo electrónico enviado. Revisa tu bandeja de entrada.",
  ERROR_FILL_IN_YOUR_EMAIL_IN_THE_FORM_FIRST:
    "Error: Completa tu correo electrónico en el formulario primero.",
  HERE: "aquí",
  NICE_TO: "MUCHO",
  MEET_YOU: "GUSTO",
  MAKE_THE_PASSWORD: "Crea una contraseña",
  NEW_PASSWORD: "Nueva contraseña",
  FULL_NAME: "Nombre completo",
  YOUR_FULL_NAME: "Tu nombre completo",
  SIGN_UP: "Crear cuenta",
  HELLO: "HOLA",
  REPEAT_AN_ORDER: "Repite un pedido",
  MY_ORDERS: "Mis pedidos",
  MY: "MIS",
  ORDERS: "PEDIDOS",
  SOJA_LOVERS: "Soja Lovers",
  LANGUAGE: "Idioma",
  FOLLOW_US: "Síguenos",
  FOLLOW_US1: "Síguenos1",
  YOU_ARE_NOT: "NO ESTAS",
  LOGGED_IN: "LOGUEADO",
  VIEW_ORDER: "Ver pedido",
  YOUR_ORDER: "TU PEDIDO",
  SIP_IN: "Para tomar aquí",
  TAKE_AWAY: "Para llevar",
  SUMMARY: "Resumen",
  TOTAL: "Total",
  CONFIRM_ORDER: "Confirmar pedido",
  MY_ORDER_1: "Mi pedido (1)",
  DELETE_ORDER: "Borrar pedido",
  COLD_OR_HOT: "¿FRÍO O CALIENTE?",
  HOW_SWEET: "¿CUÁNTO DULCE?",
  RECENT: "Recientes",
  NO_ORDER_HISTORY: "No hay pedidos",
  REPEAT: "Repetir",
  SOJA: "SOJA",
  LOVERS: "LOVERS",
  ORDER_10_BUBBLE_TEAS: "Pide 10 Bubble Teas y te invitamos al número 11",
  NO_PRODUCTS_IN_THE_CART: "No tienes productos en tu carrito",
  // descripciones
  STRAWBERRY_DESCRIPTION: "Fresas, leche de soya, bolas de tapioca.",
  BANANA_DESCRIPTION: "Plátanos, leche de soya, bolas de tapioca.",
  MANGO_DESCRIPTION: "Mango, leche de soya, bolas de tapioca.",
  TARO_MATCHA_DESCRIPTION: "Taro, matcha, leche de soya, bolas de tapioca.",
  TARO_DESCRIPTION: "Taro, leche de soya, bolas de tapioca.",
  MANGO_GRAPEFRUIT_DESCRIPTION:
    "Mango, toronja, leche de soya, bolas de tapioca.",
  YAKULT_PEACH_DESCRIPTION: "Yakult, trozos de melocotón, bolas de tapioca.",
  YAKULT_LITCHI_DESCRIPTION: "Yakult, lichi, bolas de tapioca.",
  YAKULT_GRAPEFRUIT_DESCRIPTION: "Yakult, trozos de toronja, bolas de tapioca.",
  YAKULT_PASSION_FRUIT_DESCRIPTION: "Yakult, maracuyá, bolas de tapioca.",
  SOY_MILK_DESCRIPTION: "Leche de soya, bolas de tapioca.",
  JASMINE_LATTE_DESCRIPTION: "Jazmín, leche de soya, bolas de tapioca.",
  BLACK_TEA_LATTE_DESCRIPTION: "Té negro, leche de soya, bolas de tapioca.",
  MATCHA_LATTE_DESCRIPTION: "Matcha, leche de soya, bolas de tapioca.",
  BLACK_TEA_WITH_CREAM_DESCRIPTION:
    "Té negro, leche de soya, crema de soya, bolas de tapioca.",
  JASMINE_WITH_CREAM_DESCRIPTION:
    "Té de jazmín, leche de soya, crema de soya, bolas de tapioca.",
  OOLONG_WITH_CREAM_DESCRIPTION:
    "Té oolong, leche de soya, crema de soya, bolas de tapioca.",
  sugar50: "50% azúcar",
  sugar0: "sin azúcar",
  sugar30: "30% azúcar",
  sugar70: "70% azúcar",
  hot45: "caliente (45°C)",
  hot60: "caliente (60°C)",
  noIce: "sin hielo",
  lessIce: "menos hielo",
  regularIce: "hielo regular",
};
